services:
  - type: web
    name: firmanager-frontend
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: build
    rootDir: frontend
    envVars:
      - key: NODE_VERSION
        value: 18
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
